language: node_js
node_js:
  - "0.11"
  - "0.10"
services:
  - mongodb
before_install: 
  - npm install -g grunt-cli
  - gem install compass
  - npm install -g bower
  - npm install -g nodemon
before_script: 
  - bower install
  - grunt app